baseURL = "https://lluvio.github.io/blog/"
languageCode = "en-us"
title = "Lluvio's blog"
theme = "paperback"

[params]
AuthorName = "Lluvio"
Tagline = "Hello, world!"
HomepagePosts = 10
GithubUsername = "lluvio"
disqus = "lluvio0909"

# TwitterUsername = "damiencaselli"