baseURL = "https://lluvio.github.io/blog/"
languageCode = "en-us"
title = "Lluvio's blog"
theme = "paperback"

[params]
AuthorName = "Lluvio"
Tagline = "Hello, world!"
HomepagePosts = 10
GithubUsername = "lluvio"
<<<<<<< HEAD
disqus = "lluviosblog"
toc = true
=======
disqus = "lluvio0909"

# TwitterUsername = "damiencaselli"
>>>>>>> parent of ca19714... update disqus name
